services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glycemic_map_web
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - glycemic-map-network
    restart: unless-stopped

networks:
  glycemic-map-network:
    driver: bridge