services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glycemic_map_web
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - glycemic_net
    restart: unless-stopped

networks:
  glycemic_net:
    external: true